trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Using an Ubuntu agent for the pipeline

steps:
# Checkout the code from GitHub
- task: Checkout@1
  displayName: 'Checkout GitHub repository'

# Install Databricks CLI
- script: |
    pip install databricks-cli
  displayName: 'Install Databricks CLI'