# trigger:
 #   branches:
 #     include:
 #       - main  # Trigger on changes to the main branch
 
 pool:
   vmImage: 'ubuntu-latest'  # Using an Ubuntu agent for the pipeline
 
 variables:
   - group: databricks-secret
 steps:
 # Checkout the code from GitHub
 - task: Checkout@1
   displayName: 'Checkout GitHub repository'
 
 # Install Databricks CLI
 - script: |
     pip install databricks-cli
   displayName: 'Install Databricks CLI'
 
 # Set up Databricks CLI to connect to your Databricks workspace using secrets from the Variable Group
 - script: |
     echo "Setting up Databricks CLI"
     # echo "DATABRICKS_HOST=${DATABRICKS_HOST}"  # Verify that secret variables are available
     # echo "DATABRICKS_TOKEN=${DATABRICKS_TOKEN}"  # Verify that secret variables are available
     # export DATABRICKS_HOST="${DATABRICKS_HOST}"  # Injecting secret environment variables
     # export DATABRICKS_TOKEN="${DATABRICKS_TOKEN}"  # Injecting secret environment variables
     # echo "DATABRICKS_HOST=${host}"  # Verify that secret variables are available
     # echo "DATABRICKS_TOKEN=${token}"  # Verify that secret variables are available
     export DATABRICKS_HOST=$(host)  # Injecting secret environment variables
     export DATABRICKS_TOKEN=$(token})  # Injecting secret environment variables
     export DATABRICKS_TOKEN=$(token)  # Injecting secret environment variables
     databricks --version  # Verify Databricks CLI version
   displayName: 'Configure Databricks CLI'
 
 # Clone the GitHub repository
 - script: |
     git clone https://github.com/doijadajay/Amol_Databricks.git
     cd Amol_Databricks
   displayName: 'Clone GitHub repository'
 
 # Deploy the notebook to Databricks workspace
 - script: |
     databricks workspace import --overwrite Amol_Databricks/Sample-Notebook.py /Workspace/Sample_Notebooks/Sample-Notebook.py
   displayName: 'Deploy notebook to Databricks'