trigger:
- main  # Trigger on changes to the main branch

variables:
  DATABRICKS_HOST: $(DATABRICKS_HOST)  # Set this environment variable in your Azure DevOps pipeline variables
  DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)  # Set this environment variable in your Azure DevOps pipeline variables
  NOTEBOOK_PATH: 'Sample-Notebook.py'  # Path to your notebook file in the repository
  DEPLOY_PATH: '/Workspace/Sample_Notebook'  # Path where you want to deploy the notebook in Databricks

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout the GitHub repository
- task: Checkout@1
  inputs:
    repository: 'https://github.com/doijadajay/Amol_Databricks.git'  # Your GitHub repo URL
    ref: 'refs/heads/main'  # Refers to the main branch

# Step 2: Install Databricks CLI
- script: |
    pip install databricks-cli
  displayName: 'Install Databricks CLI'

# Step 3: Set up Databricks CLI configuration
- script: |
    databricks configure --token <<EOF
    $(DATABRICKS_HOST)
    $(DATABRICKS_TOKEN)
    EOF
  displayName: 'Configure Databricks CLI'

# Step 4: Deploy the notebook to Databricks workspace
- script: |
    databricks workspace import $(Build.SourcesDirectory)/$(NOTEBOOK_PATH) --format SOURCE $(DEPLOY_PATH)
  displayName: 'Deploy notebook to Databricks'
